// Generated by gencpp from file twophase_solver_ros/CubeDefString.msg
// DO NOT EDIT!


#ifndef TWOPHASE_SOLVER_ROS_MESSAGE_CUBEDEFSTRING_H
#define TWOPHASE_SOLVER_ROS_MESSAGE_CUBEDEFSTRING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace twophase_solver_ros
{
template <class ContainerAllocator>
struct CubeDefString_
{
  typedef CubeDefString_<ContainerAllocator> Type;

  CubeDefString_()
    : CubeDefString()  {
    }
  CubeDefString_(const ContainerAllocator& _alloc)
    : CubeDefString(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _CubeDefString_type;
  _CubeDefString_type CubeDefString;





  typedef boost::shared_ptr< ::twophase_solver_ros::CubeDefString_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::twophase_solver_ros::CubeDefString_<ContainerAllocator> const> ConstPtr;

}; // struct CubeDefString_

typedef ::twophase_solver_ros::CubeDefString_<std::allocator<void> > CubeDefString;

typedef boost::shared_ptr< ::twophase_solver_ros::CubeDefString > CubeDefStringPtr;
typedef boost::shared_ptr< ::twophase_solver_ros::CubeDefString const> CubeDefStringConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::twophase_solver_ros::CubeDefString_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::twophase_solver_ros::CubeDefString_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::twophase_solver_ros::CubeDefString_<ContainerAllocator1> & lhs, const ::twophase_solver_ros::CubeDefString_<ContainerAllocator2> & rhs)
{
  return lhs.CubeDefString == rhs.CubeDefString;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::twophase_solver_ros::CubeDefString_<ContainerAllocator1> & lhs, const ::twophase_solver_ros::CubeDefString_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace twophase_solver_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::twophase_solver_ros::CubeDefString_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::twophase_solver_ros::CubeDefString_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twophase_solver_ros::CubeDefString_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twophase_solver_ros::CubeDefString_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twophase_solver_ros::CubeDefString_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twophase_solver_ros::CubeDefString_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::twophase_solver_ros::CubeDefString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3ff4760f41bf547735696b3857691d0";
  }

  static const char* value(const ::twophase_solver_ros::CubeDefString_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3ff4760f41bf547ULL;
  static const uint64_t static_value2 = 0x735696b3857691d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::twophase_solver_ros::CubeDefString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "twophase_solver_ros/CubeDefString";
  }

  static const char* value(const ::twophase_solver_ros::CubeDefString_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::twophase_solver_ros::CubeDefString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string CubeDefString\n"
;
  }

  static const char* value(const ::twophase_solver_ros::CubeDefString_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::twophase_solver_ros::CubeDefString_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.CubeDefString);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CubeDefString_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::twophase_solver_ros::CubeDefString_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::twophase_solver_ros::CubeDefString_<ContainerAllocator>& v)
  {
    s << indent << "CubeDefString: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.CubeDefString);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TWOPHASE_SOLVER_ROS_MESSAGE_CUBEDEFSTRING_H
