// Generated by gencpp from file twophase_solver_ros/SolverResponse.msg
// DO NOT EDIT!


#ifndef TWOPHASE_SOLVER_ROS_MESSAGE_SOLVERRESPONSE_H
#define TWOPHASE_SOLVER_ROS_MESSAGE_SOLVERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace twophase_solver_ros
{
template <class ContainerAllocator>
struct SolverResponse_
{
  typedef SolverResponse_<ContainerAllocator> Type;

  SolverResponse_()
    : movecount(0)
    , solution()  {
    }
  SolverResponse_(const ContainerAllocator& _alloc)
    : movecount(0)
    , solution(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _movecount_type;
  _movecount_type movecount;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _solution_type;
  _solution_type solution;





  typedef boost::shared_ptr< ::twophase_solver_ros::SolverResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::twophase_solver_ros::SolverResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SolverResponse_

typedef ::twophase_solver_ros::SolverResponse_<std::allocator<void> > SolverResponse;

typedef boost::shared_ptr< ::twophase_solver_ros::SolverResponse > SolverResponsePtr;
typedef boost::shared_ptr< ::twophase_solver_ros::SolverResponse const> SolverResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::twophase_solver_ros::SolverResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::twophase_solver_ros::SolverResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::twophase_solver_ros::SolverResponse_<ContainerAllocator1> & lhs, const ::twophase_solver_ros::SolverResponse_<ContainerAllocator2> & rhs)
{
  return lhs.movecount == rhs.movecount &&
    lhs.solution == rhs.solution;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::twophase_solver_ros::SolverResponse_<ContainerAllocator1> & lhs, const ::twophase_solver_ros::SolverResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace twophase_solver_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::twophase_solver_ros::SolverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::twophase_solver_ros::SolverResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twophase_solver_ros::SolverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twophase_solver_ros::SolverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twophase_solver_ros::SolverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twophase_solver_ros::SolverResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::twophase_solver_ros::SolverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "241bf767e2780f284a6ad3e62879583f";
  }

  static const char* value(const ::twophase_solver_ros::SolverResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x241bf767e2780f28ULL;
  static const uint64_t static_value2 = 0x4a6ad3e62879583fULL;
};

template<class ContainerAllocator>
struct DataType< ::twophase_solver_ros::SolverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "twophase_solver_ros/SolverResponse";
  }

  static const char* value(const ::twophase_solver_ros::SolverResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::twophase_solver_ros::SolverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 movecount\n"
"string solution\n"
"\n"
;
  }

  static const char* value(const ::twophase_solver_ros::SolverResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::twophase_solver_ros::SolverResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.movecount);
      stream.next(m.solution);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SolverResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::twophase_solver_ros::SolverResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::twophase_solver_ros::SolverResponse_<ContainerAllocator>& v)
  {
    s << indent << "movecount: ";
    Printer<int64_t>::stream(s, indent + "  ", v.movecount);
    s << indent << "solution: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.solution);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TWOPHASE_SOLVER_ROS_MESSAGE_SOLVERRESPONSE_H
