// Generated by gencpp from file twophase_solver_ros/Solver.msg
// DO NOT EDIT!


#ifndef TWOPHASE_SOLVER_ROS_MESSAGE_SOLVER_H
#define TWOPHASE_SOLVER_ROS_MESSAGE_SOLVER_H

#include <ros/service_traits.h>


#include <twophase_solver_ros/SolverRequest.h>
#include <twophase_solver_ros/SolverResponse.h>


namespace twophase_solver_ros
{

struct Solver
{

typedef SolverRequest Request;
typedef SolverResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Solver
} // namespace twophase_solver_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::twophase_solver_ros::Solver > {
  static const char* value()
  {
    return "3dd62463a4927de8181123eea48c8934";
  }

  static const char* value(const ::twophase_solver_ros::Solver&) { return value(); }
};

template<>
struct DataType< ::twophase_solver_ros::Solver > {
  static const char* value()
  {
    return "twophase_solver_ros/Solver";
  }

  static const char* value(const ::twophase_solver_ros::Solver&) { return value(); }
};


// service_traits::MD5Sum< ::twophase_solver_ros::SolverRequest> should match
// service_traits::MD5Sum< ::twophase_solver_ros::Solver >
template<>
struct MD5Sum< ::twophase_solver_ros::SolverRequest>
{
  static const char* value()
  {
    return MD5Sum< ::twophase_solver_ros::Solver >::value();
  }
  static const char* value(const ::twophase_solver_ros::SolverRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::twophase_solver_ros::SolverRequest> should match
// service_traits::DataType< ::twophase_solver_ros::Solver >
template<>
struct DataType< ::twophase_solver_ros::SolverRequest>
{
  static const char* value()
  {
    return DataType< ::twophase_solver_ros::Solver >::value();
  }
  static const char* value(const ::twophase_solver_ros::SolverRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::twophase_solver_ros::SolverResponse> should match
// service_traits::MD5Sum< ::twophase_solver_ros::Solver >
template<>
struct MD5Sum< ::twophase_solver_ros::SolverResponse>
{
  static const char* value()
  {
    return MD5Sum< ::twophase_solver_ros::Solver >::value();
  }
  static const char* value(const ::twophase_solver_ros::SolverResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::twophase_solver_ros::SolverResponse> should match
// service_traits::DataType< ::twophase_solver_ros::Solver >
template<>
struct DataType< ::twophase_solver_ros::SolverResponse>
{
  static const char* value()
  {
    return DataType< ::twophase_solver_ros::Solver >::value();
  }
  static const char* value(const ::twophase_solver_ros::SolverResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TWOPHASE_SOLVER_ROS_MESSAGE_SOLVER_H
