// Generated by gencpp from file twophase_solver_ros/SolveMsg.msg
// DO NOT EDIT!


#ifndef TWOPHASE_SOLVER_ROS_MESSAGE_SOLVEMSG_H
#define TWOPHASE_SOLVER_ROS_MESSAGE_SOLVEMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace twophase_solver_ros
{
template <class ContainerAllocator>
struct SolveMsg_
{
  typedef SolveMsg_<ContainerAllocator> Type;

  SolveMsg_()
    : movecount(0)
    , SolveString()  {
    }
  SolveMsg_(const ContainerAllocator& _alloc)
    : movecount(0)
    , SolveString(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _movecount_type;
  _movecount_type movecount;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _SolveString_type;
  _SolveString_type SolveString;





  typedef boost::shared_ptr< ::twophase_solver_ros::SolveMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::twophase_solver_ros::SolveMsg_<ContainerAllocator> const> ConstPtr;

}; // struct SolveMsg_

typedef ::twophase_solver_ros::SolveMsg_<std::allocator<void> > SolveMsg;

typedef boost::shared_ptr< ::twophase_solver_ros::SolveMsg > SolveMsgPtr;
typedef boost::shared_ptr< ::twophase_solver_ros::SolveMsg const> SolveMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::twophase_solver_ros::SolveMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::twophase_solver_ros::SolveMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::twophase_solver_ros::SolveMsg_<ContainerAllocator1> & lhs, const ::twophase_solver_ros::SolveMsg_<ContainerAllocator2> & rhs)
{
  return lhs.movecount == rhs.movecount &&
    lhs.SolveString == rhs.SolveString;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::twophase_solver_ros::SolveMsg_<ContainerAllocator1> & lhs, const ::twophase_solver_ros::SolveMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace twophase_solver_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::twophase_solver_ros::SolveMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::twophase_solver_ros::SolveMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twophase_solver_ros::SolveMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twophase_solver_ros::SolveMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twophase_solver_ros::SolveMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twophase_solver_ros::SolveMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::twophase_solver_ros::SolveMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8b96427a91926b7a010189fd3281ee2";
  }

  static const char* value(const ::twophase_solver_ros::SolveMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8b96427a91926b7ULL;
  static const uint64_t static_value2 = 0xa010189fd3281ee2ULL;
};

template<class ContainerAllocator>
struct DataType< ::twophase_solver_ros::SolveMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "twophase_solver_ros/SolveMsg";
  }

  static const char* value(const ::twophase_solver_ros::SolveMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::twophase_solver_ros::SolveMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 movecount\n"
"string SolveString\n"
;
  }

  static const char* value(const ::twophase_solver_ros::SolveMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::twophase_solver_ros::SolveMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.movecount);
      stream.next(m.SolveString);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SolveMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::twophase_solver_ros::SolveMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::twophase_solver_ros::SolveMsg_<ContainerAllocator>& v)
  {
    s << indent << "movecount: ";
    Printer<int64_t>::stream(s, indent + "  ", v.movecount);
    s << indent << "SolveString: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.SolveString);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TWOPHASE_SOLVER_ROS_MESSAGE_SOLVEMSG_H
